# Generated by Django 3.2.4 on 2021-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
            ],
        ),
    ]
