# Generated by Django 3.2.4 on 2021-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_viceprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='viceprincipal',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='admin/'),
        ),
    ]
